apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: httpd-example
    template: httpd-example
    type: infra-shard
  name: httpd-shard
  namespace: app-shard
spec:
  host: httpd.shard.io
  port:
    targetPort: web
  to:
    kind: Service
    name: httpd-example
    weight: 100
  wildcardPolicy: None
