apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  gateways:
    additionalIngress:
      istio-shard-ingressgateway:
        enabled: true
        namespace: istio-system-shard
        runtime:
          deployment:
            autoScaling:
              enabled: true
              maxReplicas: 4
              minReplicas: 2
        service:
          metadata:
            labels:
              app: istio-shard-ingressgateway
              istio: shard-ingressgateway
          type: NodePort
    openshiftRoute:
      enabled: true
  policy:
    type: Istiod
  profiles:
  - default
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  version: v2.1
