apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: istioinaction/shard-credential
  labels:
    type: infra-shard
  name: shard-catalog-gateway
  namespace: istio-system
spec:
  host: catalog.shard.io
  port:
    targetPort: http2
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
