apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummy
---
apiVersion: v1
kind: Service
metadata:
  name: dummy
  labels:
    app: dummy
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: dummy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: dummy
      containers:
      - name: dummy
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sleep/tls
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: dummy-secret
          optional: true
---
